### PR TITLE
Add basic HTML version of Gmail

### PR DESCRIPTION
**Pull request by darekkay**
Source: https://support.google.com/mail/answer/15049?hl=en

### CODE REVIEW

**Review by lovelldies — CHANGES_REQUESTED** [review]
Actually there is an even lighter version: https://mail.google.com/mail/x/

**Comment by darekkay** [comment]
Nice, I didn't know this one. I think both versions should be mentioned, as mine is the "classic" view that many people prefer to the new heavy one, while your version is probably best for mobile. I've updated my PR to include both versions, although I couldn't find better names than "h" and "x" to differentiate between them (from the URL) 😅

**Comment by lovelldies** [comment]
You could probably label the `h` as **Basic HTML** and the `x` as **Mobile**.

**Comment by mdibaiee** [comment]
Thanks guys! I agree with @lovelldies on the labels, and I would suggest putting them on two different list items

**Comment by darekkay** [comment]
Thanks for the suggestions, I've separated those two versions into two list items.

**Comment by mdibaiee** [comment]
Thank you @darekkay and @lovelldies !

**Pull request merged**
