### PR TITLE
Add a link to The Daily Lore

### PR DESCRIPTION
**Pull request by dguo**
https://www.dailylore.com/

Disclaimer that I own/operate this site.

### CODE REVIEW

**Comment by lovelldies** [comment]
With all due respect, I'm not sure how useful this is. But I shall leave that to @mdibaiee to decide, since he is the owner.

**Comment by dguo** [comment]
No offense taken. I just submitted it because it seems similar to some of the other ones in the news category.

**Comment by mdibaiee** [comment]
@dguo thanks for the submittion! I think the content is relevant and can of course be on the list, the only issue I see is that your website doesn't work with JavaScript disabled, which kind of goes against the idea of _lite_ websites with minimal JavaScript. If you can change your website to work without JavaScript then it's welcome on the list.

**Comment by mdibaiee** [comment]
I'm going to close this pull-request, but I'm open to re-open, and would appreciate it if the website gets to work without JavaScript. :+1:

**Pull request closed without merging**
